name: micronsbinder
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.7.0
  - pip
  - pykdtree
  - itkwidgets
  - jupyterlab>=1.0
  - jupyterlab-dash=0.1.0a3
  - dash
  - scipy
  - seaborn
  - imageio
  - nodejs
  - pip:
    - nglui
    - cloud-volume
    - annotationframeworkclient
    - meshparty
    - dashdataframe


